name: tldr
version: 0.0.1
description: >
  A simple client for tldr, a collection of simplified man pages.
author: Harry Terkelsen <harry@terkelsen.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  ansicolor: ^0.0.9
  http: ^0.11.3
  path: ^1.3.9

dev_dependencies:
  test: '>=0.12.0 <0.13.0'

executables:
  tldr:
